# Your name and what you do
name: okawara ayato
bio: Engineer

description: ayato's Personal Website

# Profile picture
picture: assets/images/icon.png

# your url: http://USERNAME.github.io
url: https://ogrew.github.io/portfolio/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
twitter: dn0t_
github: ogrew
email: dotnot905@gmail.com
instagram: ayato006
vimeo: user87601994

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Unity(C#)
    - Perl / Go / Python
    - TouchDesigner
    - Blender
    - p5.js (Processing)
    - Houdini
    - Notch
    - WebGL / GLSL
    - MySQL
    - AWS
    - Git

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Tohoku Univ. (2012-):
        name: Tohoku Univ. (2012- )
        description: Department of Electrical, Information and Physics Engineering
        url: https://www.ecei.tohoku.ac.jp/eipe
    Tohoku Univ. Master (2016-):
        name: Tohoku Univ. Master (2016-)
        description: Ohno & Fukami's Lab. (dropout)
        url: http://www.spin.riec.tohoku.ac.jp
    Kayac (2017-):
        name: Kayac (2017-)
        description: ServerSide Engineer (Perl / Go)
        url: https://www.kayac.com
    AKS (2020-):
        name: akiba.kayac.studio (2020-)
        description: Unity Engineer
        url: 

# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
